---


# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details


version: 2

build:

  os: "ubuntu-22.04"

  tools:
    python: "mambaforge-22.9"

  commands:
    # With shallow clone the "Last updated" timestamps can not get computed
    # See "Caveats" at <https://pypi.org/project/sphinx-last-updated-by-git/>
    - "git fetch --unshallow || true"
    - "mamba env create --file conda-environment.yml --force"
    - "mamba run --name mxcubeweb poetry install --only=docs,main"
    # yamllint disable-line rule:line-length
    - "mamba run --name mxcubeweb python -m sphinx -T -E -b html -d _build/doctrees -c docs docs/source ${READTHEDOCS_OUTPUT}/html"


...  # EOF
