---

# {% set data = load_setup_py_data(setup_file="./setup.py", from_recipe_dir=True) %}

package:
  name: {{data.get('name')}}
  version: {{data.get('version')}}

source:
  path: .

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."

requirements:
  host:
    - python=3.7
    - setuptools

  run:
    - python=3.7
    - pip
    - pytest
    - gevent
    - flask
    - flask-socketio
    - flask-restx
    - gevent-websocket
    - redis-py
    - scipy
    - mock
    - jsonpickle
    - pillow
    - suds-jurko
    - python-ldap
    - lxml
    - numpy
    - requests
    - scandir
    - redis
    - nodejs
    - ffmpeg
    - pytango
    - opencv
    - ruamel.yaml
    - matplotlib

test:
  imports:
    - {{data.get('name')}}

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  summary: {{data.get('description')}}
  author: {{data.get('author')}}
  description: {{data.get('description')}}
