#!/usr/bin/env python

import redis
import sys
import os

MXCUBE_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(os.path.realpath(__file__)), "./mxcube3")
)

sys.path.insert(0, MXCUBE_ROOT)

#os.environ["CUSTOM_HARDWARE_OBJECTS_PATH"] = os.path.join(
#    MXCUBE_ROOT, "HardwareRepository/HardwareObjects"
#)

#sys.path.insert(0, os.environ["CUSTOM_HARDWARE_OBJECTS_PATH"])

if __name__ == "__main__":
    db = redis.Redis()

    try:
        db.ping()
    except redis.RedisError:
        print("No Redis server is running, exiting")
        sys.exit(1)

    from mxcube3 import main

    main()