[project]
name = "mxcubeweb"
version = "4.773.0"
license = "LGPL-3.0-or-later"
description = "MXCuBE Web user interface"
authors = [
    {name = "The MXCuBE collaboration", email = "mxcube@esrf.fr"},
]
maintainers = [
    {name = "The MXCuBE collaboration", email = "mxcube@esrf.fr"},
]
readme = "README.md"
urls.homepage = "https://github.com/mxcube/mxcubeweb"
urls.repository = "https://github.com/mxcube/mxcubeweb"
urls.documentation = "https://mxcubeweb.readthedocs.io/"
keywords = ["mxcube", "mxcube3", "mxcubeweb"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: End Users/Desktop",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.10,<3.12"
scripts.mxcubeweb-server = 'mxcubeweb:main'

dependencies = [
    "authlib>=1.6.12,<2.0.0",
    "Flask>=3.1.3,<4.0.0",
    "flask-limiter>=3.12,<4.0.0",
    "flask-login>=0.6.3,<0.7.0",
    "Flask-Security[common,fsqla]==5.7.1",
    "Flask-SocketIO>=5.3.6,<6.0.0",
    "gevent>=23.9.1,<24.0.0",
    "markupsafe>=2.1.5,<3.0.0",
    "mxcubecore>=2.124.0",
    "pydantic>=2.8.2,<2.9.0",
    "pytz>=2022.6,<2023.0",
    "requests>=2.33.0,<3.0.0",
    "ruamel.yaml>=0.17.21,<0.18.0",
    "sqlalchemy>=2.0.37,<3.0.0",
    "tomli>=2.2.1,<3.0.0;python_version<=\"3.10\"",
    "tzlocal>=4.2,<5.0",
    "werkzeug>=3.1.6,<4.0.0"
]

[project.optional-dependencies]
graylog = ["graypy>=2.1.0"]

[tool.poetry]
requires-poetry = ">=2.4.2,<3.0.0"  # Keep in sync with `.pre-commit-config.yaml` and `conda-environment.yml`

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
psutil = "^5.9.4"
pytest = "^9.0.3"
pytest-cov = "^6.0.0"
ruff = "~=0.9.10"

[tool.poetry.group.docs.dependencies]
furo = "^2023.9.10"
myst-parser = "^2.0.0"
sphinx = "<7.2"
sphinx-last-updated-by-git = "^0.3.7"
sphinxcontrib-httpdomain = "^1.8.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.dependencies]
python-ldap = ">=3.4.5,<4"  # overwrite pip package with conda as there is no wheel available
ffmpeg = "*"  # Not directly used by mxcube, but necessary for the video-streamer

[tool.pixi.pypi-dependencies]
mxcubeweb = { path = ".", editable = true }

[tool.pixi.tasks.start]
args = [ { "arg" = "repository", "default" = "$PIXI_PROJECT_ROOT/demo" } ]
cmd = "mxcubeweb-server --repository {{ repository }} --static-folder $PIXI_PROJECT_ROOT/ui/build --log-level debug"

[tool.pixi.feature.ui.dependencies]
nodejs = "24.*"  # Make sure it matches `ui/package.json`
pnpm = "10.*"    # Make sure it matches `ui/package.json`

[tool.pixi.feature.ui.tasks]
pnpm = "pnpm"
_install-ui = { cmd = "pnpm --prefix ui install", inputs = ["ui/package.json"] }
build-ui = { cmd = "pnpm --prefix ui build", depends-on = ["_install-ui"] }
start-ui = { cmd = "pnpm --prefix ui start", depends-on = ["_install-ui"] }
preview-ui = { cmd = "pnpm --prefix ui start", depends-on = ["build-ui"] }

[tool.pixi.environments]
default = { solve-group = "default" }
graylog = { features = ["graylog"], solve-group = "default" }
ui = { features = ["ui"], no-default-feature = true }
