target-version = "py310"


[format]
docstring-code-format = true

[lint]
ignore = [
    "S4", # Ingore all suspicious import errors
    "B028", # Allow to use the Python standard for warnings (oneline) instead of giving explicit stacklevel
]

select = [
    "E", "F", "B", "I", "S"
]

[lint.pep8-naming]
extend-ignore-names = ["HWR"] # To avoid "N814": Camelcase `HardwareRepository` imported as constant `HWR`


[lint.per-file-ignores]
"mxcubeweb/__init__.py" = [
    "E501",
]
"mxcubeweb/app.py" = [
    "I001",
]
"mxcubeweb/core/adapter/actuator_adapter.py" = [
    "B904",
]
"mxcubeweb/core/adapter/adapter_base.py" = [
    "B904",
]
"mxcubeweb/core/adapter/motor_adapter.py" = [
    "B904",
]
"mxcubeweb/core/components/component_base.py" = [
]
"mxcubeweb/core/components/lims.py" = [
    "E501",
]
"mxcubeweb/core/components/queue.py" = [
    "B010",
    "E501",
]
"mxcubeweb/core/components/sampleview.py" = [
    "E501",
]
"mxcubeweb/core/components/user/usermanager.py" = [
    "B006",
]
"mxcubeweb/core/models/configmodels.py" = [
    "E501",
]
"mxcubeweb/core/models/generic.py" = [
    "E501",
]
"mxcubeweb/core/util/fsutils.py" = [
    "B006",
]
"mxcubeweb/logging_handler.py" = [
    "B018",
]
"mxcubeweb/routes/samplecentring.py" = [
    "E501",
]
"mxcubeweb/routes/signals.py" = [
    "B006",
]
"test/conftest.py" = [
    "E402",
    "E501",
    "S101",  # "Use of `assert` detected": ignored because tests do rely on `assert`
]
"test/test_*.py" = [
    "E712",
    "S101",  # "Use of `assert` detected": ignored because tests do rely on `assert`
]
"test/test_authn.py" = [
    "S108",
]
"test/test_diffractometer_routes.py" = [
    "S311",
]
"test/test_queue_routes.py" = [
    "E501",
]


[lint.pydocstyle]
convention = "google"
