#!/usr/bin/env bash

cd /opt/mxcubeweb/

export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"
source "$NVM_DIR/bash_completion"

redis-server&
python mxcubeweb-server --repository test/HardwareObjectsMockup.xml --log-file mxcube.log&
pnpm --prefix ui start &
