%YAML 1.2
---

# The class to initialise, and init parameters
class:
  mxcubecore.HardwareObjects.Beamline.Beamline

# objects
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
objects:
  # The !!omap and the lines starting with '- ' give you an *ordered* dictionary
  # And thus a reproducible loading order
  !!omap
  # The values are the file paths to the configuration file for the
  # object, relative to the configuration file path(s)
  #
  # NB - the order is *NOT* arbitrary, as signal connections are set
  # on one object that require the other to be already loaded.
  #
  # Hardware:
  - session: session.yaml
  - data_publisher: data_publisher.yaml
  - machine_info: machine_info.yaml
  - detector: detector.yaml
  - beam: beam.yaml
  - transmission: transmission.yaml
  - flux: flux.yaml
  - cryo: cryo.yaml
  - energy: energy.yaml
  - resolution: resolution.yaml
  - safety_shutter: safety_shutter.yaml
  - fast_shutter: fast_shutter.yaml
  - sample_changer: sample_changer.yaml
  - sample_changer_maintenance: sample_changer_maint.yaml

  # The 2 lines up have to be used for SC and the 2 line below for the plate manipulator
  # - sample_changer: plate_manipulator.xml
  # - sample_changer_maintenance: plate_manipulator_maint.xml

  # - harvester: harvester.xml
  # - harvester_maintenance: harvester_maintenance.xml

  - diffractometer: minidiff.yaml
  - lims: lims.yaml
  - sample_view: sample_view.yaml
  - queue_manager: queue_manager.yaml
  - queue_model: queue_model.yaml

  # Procedures:
  - beamline_actions: beamline_actions.yaml
  - workflow: ednaparams.yaml
  - collect: mxcollect.yaml
  - xrf_spectrum: xrf.yaml
  - energy_scan: energy_scan.yaml
  - gphl_connection: gphl/gphl-setup.yaml
  - gphl_workflow: gphl/gphl-workflow.yaml
  - xray_centring: xray_centring2.yaml
  - xml_rpc_server: xml_rpc_server.yaml

  # Analysis:
  - offline_processing: auto_processing.yaml
  - online_processing: parallel_processing.yaml
  - characterisation: characterisation.yaml

configuration:
  advanced_methods:
    - MeshScan
    - XrayCentering

  tunable_wavelength: true
  disable_num_passes: true
  run_processing_parallel: true
  run_number: 1
  click_centring_num_clicks: 3

  mesh_result_format: PNG
  use_native_mesh: true
  enable_2d_points: true

  default_acquisition_parameters:
    default:
      # Default values, also used for standard acquisition.
      # Values not given in other dictionaries are taken from here
      exp_time: 0.02  # exposure time
      osc_start: 0.0  # Only used if no current angle can be found
      osc_range: 0.1
      num_passes: 1
      first_image: 1
      overlap: 0
      num_images: 1
      detector_mode: 1  # Remove as not in practice used ?
      inverse_beam: false
      take_dark_current: true
      skip_existing_images: true
      take_snapshots: true
      sub_wedge_size: 10
      # NB 'compression' not added as apparently never used

      helical:
        # Defaults for helical scan. Missing values are taken from default
        number_of_images: 100

    characterisation:
      # Defaults for characterisation. Missing values are taken from default
      exp_time: 0.05  # exposure time
      osc_range: 1
      overlap: -89
      num_images: 4
      shutterless: false

    mesh:
      # Defaults for 'advanced' acquisition. Missing values are taken from default
      exp_time: 10  # exposure time
      range: 10
      num_images: 100
      cell_counting: zig-zag
      cell_spacing: vertical, horizontal
      mesh_center: top-left

      gphlworkflow:
        {}
        # Apparently this must be here, but we use all values same as default

    acquisition_limit_values:
      exposure_time:
        - 0.02
        - 1000
      osc_range:
        - -10000
        - 10000
      number_of_images:
        - 1
        - 99999
      kappa:
        - -5.0
        - 240.0

  available_methods:
    datacollection: true
    characterisation: true
    helical: true
    xrf_spectrum: true
    energy_scan: true
    mesh: true
    ssx_chip_collection: true
    gphlworkflow: true
    test_collection: true

    undulators:
      - type: PPU35C_GAP
        device_uri: //orion:10000/id/id/30

      - type: PPU35D_GAP
        device_uri: //orion:10000/id/id/30
