name: E2E Test

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.8"] #, "3.9", "3.10"]

    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Checkout 🏷️
        uses: actions/checkout@v3

      - name: Install LDAP dependencies
        run: sudo apt-get -y install libsasl2-dev libldap2-dev libssl-dev

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mxcubeweb
          auto-activate-base: false
          auto-update-conda: true
          environment-file: conda-environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .
          npm install --prefix ./ui

      - name: Build UI
        run: |
          npm run --prefix ./ui build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          working-directory: ui
          start: mxcubeweb-server -r ./test/HardwareObjectsMockup.xml/ --static-folder ./ui/build/ -L debug
          wait-on: "http://localhost:8081"

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Cypress debug screenshots
          path: ui/cypress/debug
