name: E2E Test

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.8"] #, "3.9", "3.10"]

    # Skip `pull_request` runs on local PRs for which `push` runs are already triggered
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install ldap dependencies
        run: sudo apt-get -y install libsasl2-dev libldap2-dev libssl-dev
      - name: Install dependencies
        run: |
          conda install -c conda-forge mamba
          mamba env update --file conda-environment.yml --name base
          pip install -e .

      - name: Cache UI dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            ui/node_modules
          key: cache-${{ runner.os }}-${{ hashFiles('ui/package-lock.json') }}

      - name: Install UI dependencies
        run: npm install --prefix ./ui --legacy-peer-deps

      - name: Build UI
        run: npm run --prefix ./ui build
        env:
          DISABLE_ESLINT_PLUGIN: true

      - name: Run MXCuBE backend
        run: mxcubeweb-server -r ./test/HardwareObjectsMockup.xml/ --static-folder $(pwd)/ui/build/ -L debug &

      - name: Run Cypress
        run: npm run --prefix ./ui e2e

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress
          path: ui/cypress/debug
